### PR TITLE
battery: Add AC icon and low_threshold config

### PR DESCRIPTION
**Pull request by kc9jud**
* When fully charged on AC, show plug character (U+1F50C).
* Add config option to show percentage even if fully charged on AC.
* Add config option to set low battery threshold.

Replaces #316

### CODE REVIEW

**Comment by kc9jud** [comment]
@jceaser Do you have Mac support?

**Comment by jceaser** [comment]
yes

**Comment by b-ryan** [comment]
:+1: looks good to me

**Comment by bre7** [comment]
pmset -g batt | egrep "([0-9]+\%)" -o

**Pull request merged**
