### PR TITLE
short path, long cwd

### PR DESCRIPTION
**Pull request by jceaser**
This change will augment the cwd display to allow for the path to be shortened while keeping the last directory (cwd) long.

Change first discussed in issue #303 .

### CODE REVIEW

**Comment by b-ryan** [comment]
hey @jceaser - thanks for the PR. This change is too complicated for such a small feature. It is too many options / too much code. I mentioned in #303 that I was leaning more toward a boolean option on whether to shorten the last directory and now feel more strongly that is what we should do.

**Comment by jceaser** [comment]
ok, I'll rework this.

**Comment by jceaser** [comment]
it's  bool and 4 lines of code. How about now?

**Comment by jceaser** [comment]
who reviews these pull requests?

**Comment by b-ryan** [comment]
I do :) Just been rather busy lately. Thanks for the change!

**Comment by jceaser** [comment]
please see #316 next

**Pull request merged**
