### PR TITLE
Redo fossil segment to use RepoStats

### PR DESCRIPTION
**Pull request by emansije**
Includes a hack to make it work in older versions of fossil that throw an error with `fossil changes --differ`, like version 1.37 does.

### CODE REVIEW

**Comment by b-ryan** [comment]
This looks great. I'm going to try to look in more detail & do some of my own testing today. I am a bit busy though so if I don't get back to you by Monday please feel free to remind me.

**Comment by emansije** [comment]
In the meanwhile I found a bug that manifested when the fossil repository had no changes in the tracked files but had untracked files. That situation would brake the parsing because it would introduce an unexpected blank element in the beginning of the status list.

**Comment by b-ryan** [comment]
@emansije how would you feel about introducing tests for this? I think the most helpful thing you could do would be to test the `parse_fossil_stats` test - you could use the `uptime_test` file as an example of how this might look.

**Comment by emansije** [comment]
Sure! I really should have implemented the tests from the start, it'd probably have saved me some time. I'll use your suggestions.

**Comment by emansije** [comment]
I can't get the test to work when the fossil segment is a threaded one, it keeps throwing this error:

```
RuntimeError: threads can only be started once
```

**Comment by b-ryan** [comment]
I just played around a bit to figure out what was going on. I made some changes here: https://github.com/banga/powerline-shell/pull/292/commits/ebb7187f04f31f522d611830217a340dbfa9453b

The issue was the use of `self.segment.start()` within a for loop in your `test_all` function. The segment is created in the `setup` function but then started multiple times within the loop. The easiest way I could figure to get around this was to just test the parsing function rather than testing the segment itself.

Let me know what you think / if you have other suggestions.

**Comment by emansije** [comment]
Looks good to me! The tests and the segment work just fine and it's a cleaner solution, too.

**Pull request merged**
