### PR TITLE
battery: Add AC icon and low_battery_threshold config

### PR DESCRIPTION
**Pull request by kc9jud**
* When fully charged on AC, show plug character (U+1F50C).
* Add config option to show percentage even if fully charged on AC.
* Add config option to set low battery threshold.

### CODE REVIEW

**Comment by kc9jud** [comment]
Oops, I guess I won’t create a separate pull request for the svn update. :-P

**Comment by jceaser** [comment]
if @b-ryan can look at this one, I have a change adding mac support, but I'm after this guy's change. My pull request in not yet pending so I can merge my code with this guys code. I do however disagree with the name of the configuration, I think the word "battery" should be dropped as it is redundent. If not done in this pull request, I will do in mine.

**Comment by kc9jud** [comment]
I'm going to go ahead and split this out into two separate PRs.

**Comment by jceaser** [comment]
@kc9jud, that sounds great, I'm still holding my code back since I made a few changes as I reworked the code a bit to make it more clear, since there is now 2 ways to get the battery info

**Pull request closed without merging**
