### PR TITLE
Add chroot segment

### PR DESCRIPTION
**Pull request by Denjag**

### CODE REVIEW

**Comment by b-ryan** [comment]
Thanks @Denjag. I'll check this out soon.

**Comment by b-ryan** [comment]
@Denjag sorry for not doing more with this sooner. I have looked at it a few times and have just been hesitant about what to do going forward. My biggest concern at the moment is that this is difficult to test. I don't ever use chroot and from my understanding, it can be somewhat intensive to set up.

**Comment by Denjag** [comment]
@b-ryan thanks for your feedback. I admit, this segment is specific and difficult to integrate simply (necessary to use symbolic links or mount bind). But it is very useful for me, and maybe, will become for another person. If it is the case, he will can just integrate this commit

**Comment by b-ryan** [comment]
Being that I cannot test this and it's been awhile without much feedback that other people want it, I'm not going to accept this. What I would rather do (and this is definitely on my todo list) is make powerline able to handle third-party segments. That way you could provide this segment as your own github repo and I could just point to it in the readme. For now though, thanks for the PR and sorry it has been sitting so long!

**Pull request closed without merging**
