### PR TITLE
Add Bazaar segment

### PR DESCRIPTION
**Pull request by emansije**
This is based on PR #162 from @1stvamp. His fork seems to be stalled, so I decided to do my own and implement the segment following the current style of the code. I'm not sure if there was a better procedure, but let me know, if that's the case, and I'll follow the instructions.

### CODE REVIEW

**Comment by b-ryan** [comment]
Excellent! Thanks @emansije 

The one change that would be great would be to use the `RepoStats` class like the git segment does: https://github.com/banga/powerline-shell/blob/master/powerline_shell/segments/git.py#L46-L57

The way you have it implemented is the way the hg & fossil ones work, but I'm hoping to update those to use this new class too. The RepoStats class helps with keeping the VCS segments consistent.

**Comment by emansije** [comment]
Oops! I based the bzr segment on the hg one, indeed, because it seemed to be the closest. I didn't realize the git segment had evolved to include a new `RepoStats` class, sorry! I'll look into it as soon as possible.

**Comment by b-ryan** [comment]
No need to be sorry - thanks!

**Comment by emansije** [comment]
The `RepoStats` class is implemented in a git perspective that doesn't fit bzr properly. I had to shoehorn bzr's file status into the existing counters in the class, like this:

bzr file status | RepoStats counters
--|--
added | staged
renamed | not_staged
modified | not_staged
kind changed | not_staged
unknown | untracked
removed | conflicted
missing | conflicted

Is it OK to leave it like that or would it be necessary to expand `RepoStats` to accommodate more generic file status?

**Comment by b-ryan** [comment]
The class is meant to be generic, despite using git terminology. I think maybe the problem is just the terminology. What I would expect is something like:

bzr file status | RepoStats existing name | RepoStats better name
--|--|--
added | staged | staged
renamed | not_staged | changed
modified | not_staged | changed
kind changed | not_staged | changed
unknown | untracked | new_file
removed | ~~conflicted~~ not_staged | changed
missing | ~~conflicted~~ not_staged | changed

The way I think about it is there are only three states that most SCM software has:

- changed = the file is tracked and has been modified in some way
- new file = the file is untracked
- conflict = the local version of the file conflicts with the upstream version

Git then has its own unique case of "staged"

Does this make sense and does it fit with bzr?

**Comment by emansije** [comment]
Looks good to me. The only thing that I'd change would be the RepoStats better name `new_file` to `new`, because bzr also tracks directories (even empty ones) and symlinks.

**Comment by b-ryan** [comment]
Yeah good call. You can feel free to leave your PR with the existing names and I can rename things (or go for it yourself if you'd like).

**Comment by emansije** [comment]
I'll be happy to do the renaming, but it'd be better to leave this PR as it is and open a new PR for the renaming, since it affects all SCM segments.

**Comment by emansije** [comment]
... I mean, it will affect *all* PR segments once they all migrate to using the RepoStats class. :smile: I was actually considering doing the migration of the hg and fossil segments, after finishing this one.

**Comment by b-ryan** [comment]
👍 all of that sounds grand

**Comment by emansije** [comment]
Are you doing a merge from this PR and then I'll start the renaming? I can do it on this branch, but I guess it would be more tidy to branch off of master after merging this PR. I'll do whatever you consider to be more practical.

**Pull request merged**
